### ISSUE TITLE
anonymize video: CUDA out of memory

### ISSUE THREAD

**Issue by sajjadaemmi** [hukkelas/DeepPrivacy#21]
i have Nvidia GPU 8 GB total capacity. i run anonymize video on a mp4 video with resolution 240x160 and lenght 00:00:01. 
and get this error:

`RuntimeError: CUDA out of memory. Tried to allocate 850.00 MiB (GPU 0; 8.00 GiB total capacity; 4.64 GiB already allocated; 298.65 MiB free; 5.96 GiB reserved in total by PyTorch)`

what is wrong?
thank you

**Comment by hukkelas** [comment]
Could you post the full stacktrace?

**Comment by sajjadaemmi** [comment]
i use small batch size and it worked. thanks
