### ISSUE TITLE
RuntimeError: CUDA error: misaligned address

### ISSUE THREAD

**Issue by a-rich** [hukkelas/DeepPrivacy#25]
Not sure why this issue is popping up now...I've run this code in the past to anonymize thousands of images...

CUDA version: 10.1

```$ uname -a
Linux learner001 4.15.0-118-generic #119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

```
>>> torch.__version__
'1.7.0.dev20200923+cu101'
>>> torchvision.__version__
'0.8.0.dev20200923+cu101'
```

```
(deep-privacy) (base) lrm@learner001:~/repos/DeepPrivacy$ python -m deep_privacy.inference.anonymize_folder models/large/config.yml --source_path /home/lrm/data/inline_2020-09-17_2020-09-18/ --target_path /home/lrm/data/anon_inline_2020-09-17_2020-09-18/

CONFIG USED:
================================================================================
logging.num_ims_per_log                            500
logging.num_ims_per_save_image                     100000
logging.num_ims_per_checkpoint                     200000
max_imsize                                         128
use_full_validation                                False
load_fraction_of_dataset                           False
dataset                                            yfcc100m128
train_config.transition_iters                      1200000
train_config.learning_rate                         0.00175
train_config.amp_opt_level                         O1
train_config.batch_size_schedule                   {4: 256, 8: 256, 16: 256, 32: 128, 64: 96, 128: 64}
models.start_channel_size                          512
models.pose_size                                   14
models.image_channels                              3
models.generator.running_average_decay             0.999
models.discriminator.structure                     normal
config_path                                        models/large/config.yml
checkpoint_dir                                     models/large/checkpoints
generated_data_dir                                 models/large/generated_data
summaries_dir                                      models/large/summaries
source_path                                        /home/lrm/data/inline_2020-09-17_2020-09-18/
target_path                                        /home/lrm/data/anon_inline_2020-09-17_2020-09-18/
================================================================================
 [*] Loading checkpoint from models/large/checkpoints/step_40000000.ckpt succeed!
extending G 512
extending G 512
extending G 512
extending G 256
extending G 128
Anonymizer initialized. Keypoint threshold: 0.3Face threshold: 0.1
Batch detecting faces:   0%|                                                                | 0/25359 [00:00<?, ?it/s]Finished loading DSFD model!
Batch detecting faces:  60%|███████████████████████████████▏                    | 15202/25359 [14:15<09:31, 17.78it/s]
Traceback (most recent call last):
  File "/home/lrm/.pyenv/versions/3.7.3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/lrm/.pyenv/versions/3.7.3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lrm/repos/DeepPrivacy/deep_privacy/inference/anonymize_folder.py", line 10, in <module>
    anonymizer.anonymize_folder(source_path, save_path)
  File "/home/lrm/repos/DeepPrivacy/deep_privacy/inference/anonymizer.py", line 35, in anonymize_folder
    im_bboxes=im_bboxes)
  File "/home/lrm/repos/DeepPrivacy/deep_privacy/inference/anonymizer.py", line 42, in anonymize_image_paths
    face_threshold=self.face_threshold
  File "/home/lrm/repos/DeepPrivacy/deep_privacy/detection/detection_api.py", line 43, in batch_detect_faces_with_keypoints
    im_bboxes = batch_detect_faces(images, face_threshold)
  File "/home/lrm/repos/DeepPrivacy/deep_privacy/detection/detection_api.py", line 25, in batch_detect_faces
    det = face_detector.detect_face(im[:, :, ::-1], face_threshold)
  File "/home/lrm/repos/DeepPrivacy/deep_privacy/detection/dsfd/detect.py", line 46, in detect_face
    y = self.net(x, confidence_threshold, self.nms_iou_threshold)
  File "/home/lrm/.pyenv/versions/deep-privacy/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lrm/repos/DeepPrivacy/deep_privacy/detection/dsfd/face_ssd.py", line 193, in forward
    nms_threshold
  File "/home/lrm/repos/DeepPrivacy/deep_privacy/detection/dsfd/utils.py", line 61, in forward
    indices = (conf_scores >= confidence_threshold).nonzero().squeeze()
RuntimeError: CUDA error: misaligned address
```

**Comment by hukkelas** [comment]
Hi, I would believe this is from your torch or torchvision version. You could try an older version Not familiar with the error

Also, we are releasing a new version of the code base next week ,which will drastically improve the generated faces.

**Comment by a-rich** [comment]
@hukkelas 

> we are releasing a new version of the code base next week ,which will drastically improve the generated faces


That's exciting -- will this be a matter of changing model structure / weights?

I tried multiple CUDA and torch versions (didn't mess around with different torchvision versions)...
Tried 10.1 / 10.2 / 11.1
Tried torch 1.5.2 / 1.6.0 / 1.7.0

I'm thinking this error must have been an `out of memory` type of thing because what ended up working for me was writing a short script to batch 5 images at a time:
```
import shutil
import os

root = '/home/lrm/data/'
src = os.path.join(root, 'original')
dst = os.path.join(root, 'anonymized')
batch_dir = os.path.join(root, 'batch')
scanner = os.scandir(src)
cmd = f"python3.8 -m deep_privacy.inference.anonymize_folder models/large/config.yml --source_path {batch_dir} --target_path {dst}"

while True:
    os.makedirs(batch_dir)
    try:
        for _ in range(5):
            f = next(scanner)
            shutil.copyfile(f.path, os.path.join(batch_dir, f.name))
        os.system(cmd)
    except StopIteration:
        if os.listdir(batch_dir):
            os.system(cmd)
        print("\nDone anonymizing images!")
    shutil.rmtree(batch_dir)
```

**Comment by hukkelas** [comment]
> That's exciting -- will this be a matter of changing model structure / weights?

Yep! You will be able to achieve better than the original "large" model (40M parameters) with only 2.8M parameters.
Also, the code-base will be completely refactored. 

As this issue will (hopefully) go away with our new release, I'm not prioritizing this issue before the new source code is released.

**Comment by jeffreyxlubin** [comment]
Hello.
Any progress on that new release?
I have been working with your code and am very interested!
Thanks.

**Comment by hukkelas** [comment]
Does this issue still exist with release 2?

**Comment by hukkelas** [comment]
Closing this issue, please reopen if the issue persists.
